-- ============================================================
-- SEED 03 — Articles (catalogue démo)  [généré par scripts/build-catalogue.mjs]
-- Idempotent : id = __demo_uid('article:<pexelsId>'), upsert on conflict.
-- Images = URLs Pexels (licence commerciale libre). 53 articles.
-- ============================================================

create or replace function public.__demo_uid(p text) returns uuid language sql immutable as $$
  select (substr(md5(p),1,8)||'-'||substr(md5(p),9,4)||'-'||substr(md5(p),13,4)||'-'||substr(md5(p),17,4)||'-'||substr(md5(p),21,12))::uuid
$$;

insert into public.articles (id, seller_user_id, seller_boutique_id, category_id, title, description, brand, condition, size, color, price, currency, images, status, is_auction, location, created_at) values
  (public.__demo_uid('article:8146450'), null, (select id from public.boutiques where handle='atelier-rive-gauche'), (select id from public.categories where slug='t-shirts-tops'), 'T-shirt en coton bio', 'T-shirt en coton bio — COS. Orange, taille XS. Neuf. Expédié depuis notre boutique à Genève.', 'COS', 'new'::public.article_condition, 'XS', 'Orange', 14.95, 'CHF', '["https://images.pexels.com/photos/8146450/pexels-photo-8146450.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '6 days'),
  (public.__demo_uid('article:8146448'), public.__demo_uid('loic.chappuis@demo.driphaus.ch'), null, (select id from public.categories where slug='t-shirts-tops'), 'Top oversize', 'Top oversize — Armedangels. Beige, taille S. Bon état. Vendu par un particulier à Lausanne.', 'Armedangels', 'good'::public.article_condition, 'S', 'Beige', 24.95, 'CHF', '["https://images.pexels.com/photos/8146448/pexels-photo-8146448.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '9 days'),
  (public.__demo_uid('article:18533669'), public.__demo_uid('camille.beguin@demo.driphaus.ch'), null, (select id from public.categories where slug='t-shirts-tops'), 'T-shirt col rond', 'T-shirt col rond — American Vintage. Beige, taille M. Bon état. Vendu par un particulier à Lausanne.', 'American Vintage', 'good'::public.article_condition, 'M', 'Beige', 34.95, 'CHF', '["https://images.pexels.com/photos/18533669/pexels-photo-18533669.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '12 days'),
  (public.__demo_uid('article:5693888'), null, (select id from public.boutiques where handle='atelier-rive-gauche'), (select id from public.categories where slug='t-shirts-tops'), 'Débardeur côtelé', 'Débardeur côtelé — Uniqlo. Gris, taille L. Très bon état. Expédié depuis notre boutique à Genève.', 'Uniqlo', 'very_good'::public.article_condition, 'L', 'Gris', 19.95, 'CHF', '["https://images.pexels.com/photos/5693888/pexels-photo-5693888.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '15 days'),
  (public.__demo_uid('article:34988575'), public.__demo_uid('loic.chappuis@demo.driphaus.ch'), null, (select id from public.categories where slug='t-shirts-tops'), 'T-shirt graphique', 'T-shirt graphique — Atelier Rive Gauche. Denim, taille XL. Très bon état. Vendu par un particulier à Lausanne.', 'Atelier Rive Gauche', 'very_good'::public.article_condition, 'XL', 'Denim', 29.95, 'CHF', '["https://images.pexels.com/photos/34988575/pexels-photo-34988575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '18 days'),
  (public.__demo_uid('article:13094187'), null, (select id from public.boutiques where handle='friperie-du-flon'), (select id from public.categories where slug='chemises-blouses'), 'Chemise en lin', 'Chemise en lin — Ralph Lauren. Beige, taille S. Neuf. Expédié depuis notre boutique à Lausanne.', 'Ralph Lauren', 'new'::public.article_condition, 'S', 'Beige', 19.95, 'CHF', '["https://images.pexels.com/photos/13094187/pexels-photo-13094187.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '2 days'),
  (public.__demo_uid('article:38561616'), public.__demo_uid('thomas.aebischer@demo.driphaus.ch'), null, (select id from public.categories where slug='chemises-blouses'), 'Chemise oxford', 'Chemise oxford — Zara. Bleu marine, taille M. Bon état. Vendu par un particulier à Neuchâtel.', 'Zara', 'good'::public.article_condition, 'M', 'Bleu marine', 39.95, 'CHF', '["https://images.pexels.com/photos/38561616/pexels-photo-38561616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Neuchâtel', now() - interval '5 days'),
  (public.__demo_uid('article:13381986'), public.__demo_uid('julien.rochat@demo.driphaus.ch'), null, (select id from public.categories where slug='chemises-blouses'), 'Blouse fluide', 'Blouse fluide — COS. Beige, taille L. Bon état. Vendu par un particulier à Genève.', 'COS', 'good'::public.article_condition, 'L', 'Beige', 54.95, 'CHF', '["https://images.pexels.com/photos/13381986/pexels-photo-13381986.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '8 days'),
  (public.__demo_uid('article:18957807'), null, (select id from public.boutiques where handle='atelier-rive-gauche'), (select id from public.categories where slug='pulls-gilets'), 'Pull en laine mérinos', 'Pull en laine mérinos — COS. Marron, taille XS. Neuf. Expédié depuis notre boutique à Genève.', 'COS', 'new'::public.article_condition, 'XS', 'Marron', 29.95, 'CHF', '["https://images.pexels.com/photos/18957807/pexels-photo-18957807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '5 days'),
  (public.__demo_uid('article:10058586'), public.__demo_uid('lea.progin@demo.driphaus.ch'), null, (select id from public.categories where slug='pulls-gilets'), 'Gilet maille torsadée', 'Gilet maille torsadée — Uniqlo. Beige, taille S. Bon état. Vendu par un particulier à Fribourg.', 'Uniqlo', 'good'::public.article_condition, 'S', 'Beige', 49.95, 'CHF', '["https://images.pexels.com/photos/10058586/pexels-photo-10058586.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Fribourg', now() - interval '8 days'),
  (public.__demo_uid('article:10154688'), public.__demo_uid('camille.beguin@demo.driphaus.ch'), null, (select id from public.categories where slug='pulls-gilets'), 'Pull col roulé', 'Pull col roulé — American Vintage. Noir, taille M. Bon état. Vendu par un particulier à Lausanne.', 'American Vintage', 'good'::public.article_condition, 'M', 'Noir', 74.95, 'CHF', '["https://images.pexels.com/photos/10154688/pexels-photo-10154688.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '11 days'),
  (public.__demo_uid('article:3799361'), null, (select id from public.boutiques where handle='atelier-rive-gauche'), (select id from public.categories where slug='pulls-gilets'), 'Cardigan oversize', 'Cardigan oversize — Benetton. Gris, taille L. Très bon état. Expédié depuis notre boutique à Genève.', 'Benetton', 'very_good'::public.article_condition, 'L', 'Gris', 34.95, 'CHF', '["https://images.pexels.com/photos/3799361/pexels-photo-3799361.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '14 days'),
  (public.__demo_uid('article:38652624'), null, (select id from public.boutiques where handle='maison-hirondelle'), (select id from public.categories where slug='robes'), 'Robe midi plissée', 'Robe midi plissée — Sézane. Beige, taille XS. Neuf. Expédié depuis notre boutique à Vevey.', 'Sézane', 'new'::public.article_condition, 'XS', 'Beige', 39.95, 'CHF', '["https://images.pexels.com/photos/38652624/pexels-photo-38652624.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Vevey', now() - interval '5 days'),
  (public.__demo_uid('article:19793984'), public.__demo_uid('sofia.moret@demo.driphaus.ch'), null, (select id from public.categories where slug='robes'), 'Robe portefeuille', 'Robe portefeuille — Maison Hirondelle. Beige, taille S. Bon état. Vendu par un particulier à Fribourg.', 'Maison Hirondelle', 'good'::public.article_condition, 'S', 'Beige', 84.95, 'CHF', '["https://images.pexels.com/photos/19793984/pexels-photo-19793984.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Fribourg', now() - interval '8 days'),
  (public.__demo_uid('article:8812795'), public.__demo_uid('elodie.favre@demo.driphaus.ch'), null, (select id from public.categories where slug='robes'), 'Robe chemise', 'Robe chemise — & Other Stories. Turquoise, taille M. Bon état. Vendu par un particulier à Nyon.', '& Other Stories', 'good'::public.article_condition, 'M', 'Turquoise', 129.95, 'CHF', '["https://images.pexels.com/photos/8812795/pexels-photo-8812795.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Nyon', now() - interval '11 days'),
  (public.__demo_uid('article:18285680'), null, (select id from public.boutiques where handle='maison-hirondelle'), (select id from public.categories where slug='robes'), 'Robe de soirée', 'Robe de soirée — Ba&sh. Kaki, taille L. Très bon état. Expédié depuis notre boutique à Vevey.', 'Ba&sh', 'very_good'::public.article_condition, 'L', 'Kaki', 54.95, 'CHF', '["https://images.pexels.com/photos/18285680/pexels-photo-18285680.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Vevey', now() - interval '14 days'),
  (public.__demo_uid('article:16358959'), public.__demo_uid('sofia.moret@demo.driphaus.ch'), null, (select id from public.categories where slug='robes'), 'Robe en maille', 'Robe en maille — Zara. Beige, taille XS. Très bon état. Vendu par un particulier à Fribourg.', 'Zara', 'very_good'::public.article_condition, 'XS', 'Beige', 99.95, 'CHF', '["https://images.pexels.com/photos/16358959/pexels-photo-16358959.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Fribourg', now() - interval '17 days'),
  (public.__demo_uid('article:20143795'), null, (select id from public.boutiques where handle='friperie-du-flon'), (select id from public.categories where slug='jeans'), 'Jean droit brut', 'Jean droit brut — Levi''s. Gris, taille W28. Neuf. Expédié depuis notre boutique à Lausanne.', 'Levi''s', 'new'::public.article_condition, 'W28', 'Gris', 24.95, 'CHF', '["https://images.pexels.com/photos/20143795/pexels-photo-20143795.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '5 days'),
  (public.__demo_uid('article:18533668'), public.__demo_uid('julien.rochat@demo.driphaus.ch'), null, (select id from public.categories where slug='jeans'), 'Jean mom taille haute', 'Jean mom taille haute — Nudie Jeans. Gris, taille W29. Bon état. Vendu par un particulier à Genève.', 'Nudie Jeans', 'good'::public.article_condition, 'W29', 'Gris', 54.95, 'CHF', '["https://images.pexels.com/photos/18533668/pexels-photo-18533668.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '8 days'),
  (public.__demo_uid('article:9311620'), public.__demo_uid('thomas.aebischer@demo.driphaus.ch'), null, (select id from public.categories where slug='jeans'), 'Jean slim délavé', 'Jean slim délavé — Weekday. Marron, taille W30. Bon état. Vendu par un particulier à Neuchâtel.', 'Weekday', 'good'::public.article_condition, 'W30', 'Marron', 89.95, 'CHF', '["https://images.pexels.com/photos/9311620/pexels-photo-9311620.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Neuchâtel', now() - interval '11 days'),
  (public.__demo_uid('article:13094233'), null, (select id from public.boutiques where handle='atelier-rive-gauche'), (select id from public.categories where slug='vestes-manteaux'), 'Manteau en laine', 'Manteau en laine — COS. Gris, taille S. Neuf. Expédié depuis notre boutique à Genève.', 'COS', 'new'::public.article_condition, 'S', 'Gris', 49.95, 'CHF', '["https://images.pexels.com/photos/13094233/pexels-photo-13094233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '1 days'),
  (public.__demo_uid('article:8743972'), null, (select id from public.boutiques where handle='friperie-du-flon'), (select id from public.categories where slug='vestes-manteaux'), 'Veste en jean', 'Veste en jean — Levi''s. Gris, taille M. Très bon état. Expédié depuis notre boutique à Lausanne.', 'Levi''s', 'very_good'::public.article_condition, 'M', 'Gris', 119.95, 'CHF', '["https://images.pexels.com/photos/8743972/pexels-photo-8743972.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '4 days'),
  (public.__demo_uid('article:5771897'), public.__demo_uid('marine.dubois@demo.driphaus.ch'), null, (select id from public.categories where slug='vestes-manteaux'), 'Blazer oversize', 'Blazer oversize — Sandro. Gris, taille L. Bon état. Vendu par un particulier à Morges.', 'Sandro', 'good'::public.article_condition, 'L', 'Gris', 189.95, 'CHF', '["https://images.pexels.com/photos/5771897/pexels-photo-5771897.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Morges', now() - interval '7 days'),
  (public.__demo_uid('article:5970834'), null, (select id from public.boutiques where handle='atelier-rive-gauche'), (select id from public.categories where slug='vestes-manteaux'), 'Trench-coat', 'Trench-coat — Burberry. Rose, taille XL. Très bon état. Expédié depuis notre boutique à Genève.', 'Burberry', 'very_good'::public.article_condition, 'XL', 'Rose', 69.95, 'CHF', '["https://images.pexels.com/photos/5970834/pexels-photo-5970834.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '10 days'),
  (public.__demo_uid('article:1464625'), public.__demo_uid('julien.rochat@demo.driphaus.ch'), null, (select id from public.categories where slug='baskets-sneakers'), 'Sneakers basses en cuir', 'Sneakers basses en cuir — Nike. Blanc, taille 39. Très bon état. Vendu par un particulier à Genève.', 'Nike', 'very_good'::public.article_condition, '39', 'Blanc', 34.95, 'CHF', '["https://images.pexels.com/photos/1464625/pexels-photo-1464625.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '2 days'),
  (public.__demo_uid('article:1461048'), public.__demo_uid('noe.girard@demo.driphaus.ch'), null, (select id from public.categories where slug='baskets-sneakers'), 'Baskets running rétro', 'Baskets running rétro — Adidas. Blanc, taille 40. Bon état. Vendu par un particulier à Sion.', 'Adidas', 'good'::public.article_condition, '40', 'Blanc', 79.95, 'CHF', '["https://images.pexels.com/photos/1461048/pexels-photo-1461048.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Sion', now() - interval '5 days'),
  (public.__demo_uid('article:26852497'), public.__demo_uid('loic.chappuis@demo.driphaus.ch'), null, (select id from public.categories where slug='baskets-sneakers'), 'Sneakers montantes', 'Sneakers montantes — New Balance. Beige, taille 41. Bon état. Vendu par un particulier à Lausanne.', 'New Balance', 'good'::public.article_condition, '41', 'Beige', 119.95, 'CHF', '["https://images.pexels.com/photos/26852497/pexels-photo-26852497.png?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '8 days'),
  (public.__demo_uid('article:19845610'), public.__demo_uid('julien.rochat@demo.driphaus.ch'), null, (select id from public.categories where slug='baskets-sneakers'), 'Baskets en toile', 'Baskets en toile — Veja. Noir, taille 42. État correct. Vendu par un particulier à Genève.', 'Veja', 'fair'::public.article_condition, '42', 'Noir', 49.95, 'CHF', '["https://images.pexels.com/photos/19845610/pexels-photo-19845610.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '11 days'),
  (public.__demo_uid('article:19869760'), public.__demo_uid('noe.girard@demo.driphaus.ch'), null, (select id from public.categories where slug='baskets-sneakers'), 'Sneakers chunky', 'Sneakers chunky — Converse. Turquoise, taille 43. Très bon état. Vendu par un particulier à Sion.', 'Converse', 'very_good'::public.article_condition, '43', 'Turquoise', 89.95, 'CHF', '["https://images.pexels.com/photos/19869760/pexels-photo-19869760.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Sion', now() - interval '14 days'),
  (public.__demo_uid('article:26861940'), null, (select id from public.boutiques where handle='friperie-du-flon'), (select id from public.categories where slug='bottes-bottines'), 'Bottines en cuir', 'Bottines en cuir — Dr. Martens. Blanc, taille 37. Neuf. Expédié depuis notre boutique à Lausanne.', 'Dr. Martens', 'new'::public.article_condition, '37', 'Blanc', 39.95, 'CHF', '["https://images.pexels.com/photos/26861940/pexels-photo-26861940.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '1 days'),
  (public.__demo_uid('article:26732212'), public.__demo_uid('marine.dubois@demo.driphaus.ch'), null, (select id from public.categories where slug='bottes-bottines'), 'Boots Chelsea', 'Boots Chelsea — Clarks. Beige, taille 38. Bon état. Vendu par un particulier à Morges.', 'Clarks', 'good'::public.article_condition, '38', 'Beige', 89.95, 'CHF', '["https://images.pexels.com/photos/26732212/pexels-photo-26732212.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Morges', now() - interval '4 days'),
  (public.__demo_uid('article:26774381'), public.__demo_uid('elodie.favre@demo.driphaus.ch'), null, (select id from public.categories where slug='bottes-bottines'), 'Bottes hautes', 'Bottes hautes — Sézane. Beige, taille 39. Bon état. Vendu par un particulier à Nyon.', 'Sézane', 'good'::public.article_condition, '39', 'Beige', 144.95, 'CHF', '["https://images.pexels.com/photos/26774381/pexels-photo-26774381.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Nyon', now() - interval '7 days'),
  (public.__demo_uid('article:26587312'), null, (select id from public.boutiques where handle='friperie-du-flon'), (select id from public.categories where slug='bottes-bottines'), 'Bottines à lacets', 'Bottines à lacets — Vagabond. Beige, taille 40. Très bon état. Expédié depuis notre boutique à Lausanne.', 'Vagabond', 'very_good'::public.article_condition, '40', 'Beige', 54.95, 'CHF', '["https://images.pexels.com/photos/26587312/pexels-photo-26587312.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '10 days'),
  (public.__demo_uid('article:26856056'), public.__demo_uid('marine.dubois@demo.driphaus.ch'), null, (select id from public.categories where slug='bottes-bottines'), 'Boots à talon', 'Boots à talon — Timberland. Blanc, taille 41. Très bon état. Vendu par un particulier à Morges.', 'Timberland', 'very_good'::public.article_condition, '41', 'Blanc', 104.95, 'CHF', '["https://images.pexels.com/photos/26856056/pexels-photo-26856056.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Morges', now() - interval '13 days'),
  (public.__demo_uid('article:27046146'), null, (select id from public.boutiques where handle='maison-hirondelle'), (select id from public.categories where slug='sacs-a-main'), 'Sac cabas en cuir', 'Sac cabas en cuir — Longchamp. Beige, taille Unique. Neuf. Expédié depuis notre boutique à Vevey.', 'Longchamp', 'new'::public.article_condition, 'Unique', 'Beige', 44.95, 'CHF', '["https://images.pexels.com/photos/27046146/pexels-photo-27046146.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Vevey', now() - interval '4 days'),
  (public.__demo_uid('article:27046143'), public.__demo_uid('marine.dubois@demo.driphaus.ch'), null, (select id from public.categories where slug='sacs-a-main'), 'Sac porté épaule', 'Sac porté épaule — Michael Kors. Beige, taille Unique. Bon état. Vendu par un particulier à Morges.', 'Michael Kors', 'good'::public.article_condition, 'Unique', 'Beige', 124.95, 'CHF', '["https://images.pexels.com/photos/27046143/pexels-photo-27046143.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Morges', now() - interval '7 days'),
  (public.__demo_uid('article:26736144'), public.__demo_uid('sofia.moret@demo.driphaus.ch'), null, (select id from public.categories where slug='sacs-a-main'), 'Sac seau', 'Sac seau — Polène. Gris, taille Unique. Bon état. Vendu par un particulier à Fribourg.', 'Polène', 'good'::public.article_condition, 'Unique', 'Gris', 204.95, 'CHF', '["https://images.pexels.com/photos/26736144/pexels-photo-26736144.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Fribourg', now() - interval '10 days'),
  (public.__demo_uid('article:34976481'), null, (select id from public.boutiques where handle='maison-hirondelle'), (select id from public.categories where slug='sacs-a-main'), 'Sac à main structuré', 'Sac à main structuré — Maison Hirondelle. Beige, taille Unique. Très bon état. Expédié depuis notre boutique à Vevey.', 'Maison Hirondelle', 'very_good'::public.article_condition, 'Unique', 'Beige', 69.95, 'CHF', '["https://images.pexels.com/photos/34976481/pexels-photo-34976481.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Vevey', now() - interval '13 days'),
  (public.__demo_uid('article:27046147'), public.__demo_uid('marine.dubois@demo.driphaus.ch'), null, (select id from public.categories where slug='sacs-a-main'), 'Sac hobo', 'Sac hobo — Coach. Gris, taille Unique. Très bon état. Vendu par un particulier à Morges.', 'Coach', 'very_good'::public.article_condition, 'Unique', 'Gris', 149.95, 'CHF', '["https://images.pexels.com/photos/27046147/pexels-photo-27046147.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Morges', now() - interval '16 days'),
  (public.__demo_uid('article:8839887'), public.__demo_uid('thomas.aebischer@demo.driphaus.ch'), null, (select id from public.categories where slug='montres'), 'Montre automatique', 'Montre automatique — Seiko. Bleu marine, taille Unique. Très bon état. Vendu par un particulier à Neuchâtel.', 'Seiko', 'very_good'::public.article_condition, 'Unique', 'Bleu marine', 59.95, 'CHF', '["https://images.pexels.com/photos/8839887/pexels-photo-8839887.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Neuchâtel', now() - interval '0 days'),
  (public.__demo_uid('article:6157408'), public.__demo_uid('julien.rochat@demo.driphaus.ch'), null, (select id from public.categories where slug='montres'), 'Montre chronographe', 'Montre chronographe — Casio. Gris, taille Unique. Bon état. Vendu par un particulier à Genève.', 'Casio', 'good'::public.article_condition, 'Unique', 'Gris', 154.95, 'CHF', '["https://images.pexels.com/photos/6157408/pexels-photo-6157408.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '3 days'),
  (public.__demo_uid('article:14312717'), public.__demo_uid('noe.girard@demo.driphaus.ch'), null, (select id from public.categories where slug='montres'), 'Montre habillée', 'Montre habillée — Tissot. Gris, taille Unique. Bon état. Vendu par un particulier à Sion.', 'Tissot', 'good'::public.article_condition, 'Unique', 'Gris', 249.95, 'CHF', '["https://images.pexels.com/photos/14312717/pexels-photo-14312717.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Sion', now() - interval '6 days'),
  (public.__demo_uid('article:6157411'), public.__demo_uid('thomas.aebischer@demo.driphaus.ch'), null, (select id from public.categories where slug='montres'), 'Montre vintage', 'Montre vintage — Citizen. Gris, taille Unique. État correct. Vendu par un particulier à Neuchâtel.', 'Citizen', 'fair'::public.article_condition, 'Unique', 'Gris', 89.95, 'CHF', '["https://images.pexels.com/photos/6157411/pexels-photo-6157411.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Neuchâtel', now() - interval '9 days'),
  (public.__demo_uid('article:9261531'), public.__demo_uid('julien.rochat@demo.driphaus.ch'), null, (select id from public.categories where slug='montres'), 'Montre à quartz', 'Montre à quartz — Swatch. Bleu marine, taille Unique. Très bon état. Vendu par un particulier à Genève.', 'Swatch', 'very_good'::public.article_condition, 'Unique', 'Bleu marine', 184.95, 'CHF', '["https://images.pexels.com/photos/9261531/pexels-photo-9261531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Genève', now() - interval '12 days'),
  (public.__demo_uid('article:32677231'), public.__demo_uid('elodie.favre@demo.driphaus.ch'), null, (select id from public.categories where slug='lunettes-soleil'), 'Lunettes de soleil rondes', 'Lunettes de soleil rondes — Ray-Ban. Beige, taille Unique. Très bon état. Vendu par un particulier à Nyon.', 'Ray-Ban', 'very_good'::public.article_condition, 'Unique', 'Beige', 24.95, 'CHF', '["https://images.pexels.com/photos/32677231/pexels-photo-32677231.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Nyon', now() - interval '1 days'),
  (public.__demo_uid('article:32677251'), public.__demo_uid('marine.dubois@demo.driphaus.ch'), null, (select id from public.categories where slug='lunettes-soleil'), 'Lunettes aviateur', 'Lunettes aviateur — Persol. Blanc, taille Unique. Bon état. Vendu par un particulier à Morges.', 'Persol', 'good'::public.article_condition, 'Unique', 'Blanc', 64.95, 'CHF', '["https://images.pexels.com/photos/32677251/pexels-photo-32677251.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Morges', now() - interval '4 days'),
  (public.__demo_uid('article:32677225'), public.__demo_uid('sofia.moret@demo.driphaus.ch'), null, (select id from public.categories where slug='lunettes-soleil'), 'Lunettes œil-de-chat', 'Lunettes œil-de-chat — Le Specs. Beige, taille Unique. Bon état. Vendu par un particulier à Fribourg.', 'Le Specs', 'good'::public.article_condition, 'Unique', 'Beige', 104.95, 'CHF', '["https://images.pexels.com/photos/32677225/pexels-photo-32677225.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Fribourg', now() - interval '7 days'),
  (public.__demo_uid('article:32677211'), public.__demo_uid('elodie.favre@demo.driphaus.ch'), null, (select id from public.categories where slug='lunettes-soleil'), 'Lunettes carrées', 'Lunettes carrées — Komono. Blanc, taille Unique. État correct. Vendu par un particulier à Nyon.', 'Komono', 'fair'::public.article_condition, 'Unique', 'Blanc', 34.95, 'CHF', '["https://images.pexels.com/photos/32677211/pexels-photo-32677211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Nyon', now() - interval '10 days'),
  (public.__demo_uid('article:32677205'), public.__demo_uid('marine.dubois@demo.driphaus.ch'), null, (select id from public.categories where slug='lunettes-soleil'), 'Lunettes rétro', 'Lunettes rétro — Chimi. Rose, taille Unique. Très bon état. Vendu par un particulier à Morges.', 'Chimi', 'very_good'::public.article_condition, 'Unique', 'Rose', 74.95, 'CHF', '["https://images.pexels.com/photos/32677205/pexels-photo-32677205.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Morges', now() - interval '13 days'),
  (public.__demo_uid('article:30982135'), null, (select id from public.boutiques where handle='maison-hirondelle'), (select id from public.categories where slug='echarpes-foulards'), 'Écharpe en laine', 'Écharpe en laine — Acne Studios. Beige, taille Unique. Neuf. Expédié depuis notre boutique à Vevey.', 'Acne Studios', 'new'::public.article_condition, 'Unique', 'Beige', 19.95, 'CHF', '["https://images.pexels.com/photos/30982135/pexels-photo-30982135.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Vevey', now() - interval '3 days'),
  (public.__demo_uid('article:30550128'), public.__demo_uid('lea.progin@demo.driphaus.ch'), null, (select id from public.categories where slug='echarpes-foulards'), 'Foulard en soie', 'Foulard en soie — Sézane. Beige, taille Unique. Bon état. Vendu par un particulier à Fribourg.', 'Sézane', 'good'::public.article_condition, 'Unique', 'Beige', 49.95, 'CHF', '["https://images.pexels.com/photos/30550128/pexels-photo-30550128.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Fribourg', now() - interval '6 days'),
  (public.__demo_uid('article:30982096'), public.__demo_uid('camille.beguin@demo.driphaus.ch'), null, (select id from public.categories where slug='echarpes-foulards'), 'Étole oversize', 'Étole oversize — Maison Hirondelle. Beige, taille Unique. Bon état. Vendu par un particulier à Lausanne.', 'Maison Hirondelle', 'good'::public.article_condition, 'Unique', 'Beige', 74.95, 'CHF', '["https://images.pexels.com/photos/30982096/pexels-photo-30982096.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Lausanne', now() - interval '9 days'),
  (public.__demo_uid('article:8850650'), null, (select id from public.boutiques where handle='maison-hirondelle'), (select id from public.categories where slug='echarpes-foulards'), 'Écharpe à franges', 'Écharpe à franges — COS. Gris, taille Unique. Très bon état. Expédié depuis notre boutique à Vevey.', 'COS', 'very_good'::public.article_condition, 'Unique', 'Gris', 29.95, 'CHF', '["https://images.pexels.com/photos/8850650/pexels-photo-8850650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"]'::jsonb, 'active', false, 'Vevey', now() - interval '12 days')
on conflict (id) do update set
  seller_user_id=excluded.seller_user_id, seller_boutique_id=excluded.seller_boutique_id, category_id=excluded.category_id,
  title=excluded.title, description=excluded.description, brand=excluded.brand, condition=excluded.condition,
  size=excluded.size, color=excluded.color, price=excluded.price, images=excluded.images, status=excluded.status, location=excluded.location;
